### ISSUE TITLE
Cannot process object

### ISSUE THREAD

**Issue by aski71** [iobroker-community-adapters/ioBroker.fhem#203]
Hi, seit dem Upgrade auf 2.0.2 hagelt es bei mir ständig Fehlermeldungen nachfolgender Art.
Löschen des fhem-Objektbaums und Downgrade auf 2.0.0 hat nichts gebracht.
Nach Löschen des fhem-Objektbaums und Downgrade auf 1.6.3 geht's wieder.

`2022-12-29 10:04:23.122  - error: fhem.0 (16277) Cannot process object: fhem.0.UNIFI.<BINARY> > TypeError: val.split is not a function {"Name":"UNIFI","PossibleSets":"<BINARY>","PossibleAttrs":"alias comment:textField-long eventMap:textField-long group room suppressReading userattr userReadings:textField-long verbose:0,1,2,3,4,5  disable:1,0 devAlias ignoreWiredClients:1,0 ignoreWirelessClients:1,0 httpLoglevel:1,2,3,4,5 eventPeriod voucherCache customClientReadings:textField-long customClientNames isUDM:0,1 event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading cmdIcon devStateIcon devStateIcon:textField-long devStateStyle fp_Home3D fp_fpBatteries genericDeviceType:ignore,switch,outlet,light,blind,contact,thermometer,thermostat,garage,window,lock ... <ellenlanger String von irgendwelchen UNIFI wifi Geräten und weiß Gott welcher Konfigurationen aus fhem> ... }} [main] [eventFHEM] [processEvent] [parseEvent] [doJsonlist] [checkQueue] [processQueue] [requestMeta] [parseObjects] 
`

`
2022-12-29 10:08:40.648  - error: fhem.0 (30902) Cannot process object: fhem.0.SeitenMarkise.pct > TypeError: val.split is not a function {"Name":"SeitenMarkise","PossibleSets":"clear defaults:reset,update,old,forceReset readingFilter:multiple-strict,0.AES_KEY,0.CONFIG_PENDING,0.DUTYCYCLE,0.RSSI_DEVICE,0.RSSI_PEER,0.STICKY_UNREACH,0.UNREACH,1.DIRECTION,1.INHIBIT,1.LEVEL,1.WORKING config datapoint close:noArg down up stop:noArg open:noArg oldPos:noArg pct toggle:noArg","PossibleAttrs":"alias comment:textField-long eventMap:textField-long group room suppressReading userattr userReadings:textField-long verbose:0,1,2,3,4,5  IODev ccuaggregate:textField-long ccucalculate:textField-long ccuflags:multiple-strict,ackState,hideStdReadings,replaceStdReadings,noBoundsChecking,logCommand,noReadings,trace,simulate,showMasterReadings,showLinkReadings,showDeviceReadings,showServiceReadings ccureadingfilter:textField-long ccureadingformat:name,namelc,address,addresslc,datapoint,datapointlc ccureadingname:textField-long ccuSetOnChange ccuReadingPrefix devStateFlags ccuget:State,Value ccuscaleval ccuverify:0,1,2 disable:0,1 hmstatevals:textField-long statevals substexcl substitute:textField-long statechannel controlchannel stripnumber peer:textField-long traceFilter event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading statedatapoint:select,1.LEVEL controldatapoint:select,1.LEVEL cmdIcon devStateIcon devStateIcon:textField-long devStateStyle fp_Home3D fp_fpBatteries genericDeviceType:ignore,switch,outlet,light,blind,contact,thermometer,thermostat,garage,window,lock homebridgeMapping:textField-long icon lightSceneParamsToSave lightSceneRestoreOnlyIfChanged:1,0 siriName sortby webCmd webCmdLabel:textField-long widgetOverride","Internals":{"DEF":"LEQ0801968 1","FUUID":"5c4afdb9-f33f-2248-8df8-dab825cbdefd972a","IODev":"ccu2","NAME":"SeitenMarkise","NR":"197","STATE":"open","TYPE":"HMCCUDEV","ccuaddr":"LEQ0801968","ccudevstate":"active","ccuif":"BidCos-RF","ccuname":"Seitenmarkise","ccurolectrl":"BLIND","ccurolestate":"BLIND","ccusubtype":"HM-LC-Bl1-SM","ccutype":"HM-LC-Bl1-SM","eventCount":"13","firmware":"1.7","readonly":"no","sender":"ccu:Display-Taster"},"Readings":{"1.DIRECTION":{"Value":"none","Time":"2022-12-28 22:38:02"},"1.INHIBIT":{"Value":"false","Time":"2022-12-22 13:37:04"},"1.LEVEL":{"Value":"open","Time":"2022-12-28 22:38:02"},"1.WORKING":{"Value":"no","Time":"2022-12-28 22:38:02"},"IODev":{"Value":"ccu2","Time":"2022-12-22 13:36:31"},"activity":{"Value":"alive","Time":"2022-12-22 13:37:04"},"control":{"Value":"open","Time":"2022-12-28 22:38:02"},"devstate":{"Value":"ok","Time":"2022-12-28 22:38:02"},"hmstate":{"Value":"open","Time":"2022-12-28 22:38:02"},"level":{"Value":"open","Time":"2022-12-28 22:38:02"},"pct":{"Value":"100","Time":"2022-12-28 22:38:02"},"rssidevice":{"Value":"-255","Time":"2022-12-22 13:37:04"},"rssipeer":{"Value":"-190","Time":"2022-12-22 13:37:04"},"sign":{"Value":"on","Time":"2022-12-22 13:37:04"},"state":{"Value":"open","Time":"2022-12-28 22:38:02"}},"Attributes":{"IODev":"ccu2","alias":"SeitenMarkise","ccuverify":"2","cmdIcon":"open:fts_shutter_up stop:fts_shutter_manual close:fts_shutter_down","controlchannel":"1","fp_Home3D":"705,22,2,SeitenMarkise,","genericDeviceType":"blind","homebridgeMapping":"CurrentPosition=pct TargetPosition=pct::pct PositionState=1.DIRECTION,values=none:STOPPED;down:DECREASING;up:INCREASING","room":"Balkon,HomekitActors","siriName":"Blende","substexcl":"pct","webCmd":"pct:open:close:stop","widgetOverride":"pct:slider,0,10,100"}} [main] [syncFHEM] [parseObjects] `

**Comment by LausiD** [comment]
Bitte teste mal die Version vom 16.07.22 direkt von github

**Comment by aski71** [comment]
Direkt von github installiert: Gleiches Problem.

**Comment by D3ltorohd** [comment]
Ich hänge mich hier mal mit an, selbige Probleme mit FHEM und dem Rollo Modul. Mit den beiden letzten 2er Versionen fehlt mir dort ein DP den es schon seit Ewigkeiten gibt. Mein VIS und alles baut darauf auf. Jetzt bin ich zurück auf die v 1.6.3 und der DP war sofort wieder da und läuft wieder so wies soll.

**Comment by Apollon77** [comment]
Ok, bitte mal einer GitHub version installieren und dann Fehlerlog (und bitte vollstndig und nicht gekürzt!) hier posten oder also File attachen. Jetzt sollte die Code-Stelle mitgeloggt werden wo der Fehler genau auftritt.

@D3ltorohd 
> fehlt mir dort ein DP den es schon seit Ewigkeiten gibt.

In der Annahme das es "einfach nur" ein Fehler ist weil das entsprechende Objekt nicht verarbeitet werden kann ists ok .. aber bitte sei doch in Zukunft eeetwasss genauer ... ;-)

**Comment by aski71** [comment]
Hallo Ingo,
hier nochmal ein Log.
Da es sich bei dem Objekt um einen UNIFI Access Point handelt, dennoch verkürzt, weil ich ein wenig Vorbehalte habe, meine ganze interne Netzwerktopologie und SSID öffentlich zu publishen.
Solltest Du mehr benötigen, gerne in einem 1:1 Austausch.

`2023-01-02 17:00:08.038  - debug: fhem.0 (25420) [main] [processQueue] [requestMeta] [parseObjects] check channel fhem.0.UNIFI | name: UNIFI | room: Zentral | role: undefined | function: no |  1/1
2023-01-02 17:00:08.043  - error: fhem.0 (25420) Cannot process object: fhem.0.UNIFI.<BINARY> > TypeError: val.split is not a function {"Name":"UNIFI","PossibleSets":"<BINARY>","PossibleAttrs":"alias comment:textField-long eventMap:textField-long group room suppressReading userattr userReadings:textField-long verbose:0,1,2,3,4,5  disable:1,0 devAlias ignoreWiredClients:1,0 ignoreWirelessClients:1,0 httpLoglevel:1,2,3,4,5 eventPeriod voucherCache customClientReadings:textField-long customClientNames isUDM:0,1 event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading cmdIcon devStateIcon devStateIcon:textField-long devStateStyle fp_Home3D fp_fpBatteries genericDeviceType:ignore,switch,outlet,light,blind,contact,thermometer,thermostat,garage,window,lock homebridgeMapping:textField-long icon lightSceneParamsToSave lightSceneRestoreOnlyIfChanged:1,0 siriName sortby webCmd webCmdLabel:textField-long widgetOverride","Internals":{ <...> } [main] [processQueue] [requestMeta] [parseObjects] 
2023-01-02 17:00:08.044  - error: fhem.0 (25420) TypeError: val.split is not a function
    at parseObjects (/opt/iobroker/node_modules/iobroker.fhem/main.js:1269:55)
    at Telnet.requestCB (/opt/iobroker/node_modules/iobroker.fhem/main.js:2353:17)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.fhem/lib/telnet.js:141:30)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) [main] [processQueue] [requestMeta] [parseObjects] `

**Comment by D3ltorohd** [comment]
> Ok, bitte mal einer GitHub version installieren und dann Fehlerlog (und bitte vollstndig und nicht gekürzt!) hier posten oder also File attachen. Jetzt sollte die Code-Stelle mitgeloggt werden wo der Fehler genau auftritt.
> 
> @D3ltorohd
> 
> > fehlt mir dort ein DP den es schon seit Ewigkeiten gibt.
> 
> In der Annahme das es "einfach nur" ein Fehler ist weil das entsprechende Objekt nicht verarbeitet werden kann ists ok .. aber bitte sei doch in Zukunft eeetwasss genauer ... ;-)

Bei meinem Problem geht es um den DP als Beispiel 

`fhem.0.Buero_li.pct`

auf der FHEM Seite ist es dieser hier 

`ReadingsVal('Buero_li', 'pct', '');
[Buero_li:pct]
[r:Buero_li:pct]
Buero_li:pct:.*`

[Log](https://forum.iobroker.net/assets/uploads/files/1672508606270-log-ausschnitt.txt) mit Version 2.0.2 falls das was bringt, die Github muss ich erst noch mal installieren.

**Comment by Apollon77** [comment]
Ok, GitHub bitte versuchen.Den Fehler in Zeile 1269 der hier @aski71 hatte sollte weg sein ... Interessanterweise war ein Wert der als zeichenkette erwartet war ... aber keine Zeichenkette war. Wird jetzt konvertiert. Also ggf ist da noch was anderes komisch, aber mal schauen wo wir damit jetzt enden

**Comment by aski71** [comment]
Adapter von Github startet jetzt ohne Fehlermeldung.

**Comment by Apollon77** [comment]
Und alle Objekte sind da?

@D3ltorohd Kannst DU bitte auch versuchen?

**Comment by LausiD** [comment]
Zeile 1254 geändert, damit sollte das Problem behoben sein :-)
Bitte github Version erneut installieren.

**Comment by Apollon77** [comment]
Ok, ja so geht es auch

**Comment by aski71** [comment]
> Und alle Objekte sind da?
> 

Es sieht so aus, ja.
Trotzdem nochmal die github Version installieren?

**Comment by Apollon77** [comment]
Release geht raus

**Comment by D3ltorohd** [comment]
So hab eben auch die neue Github Version installiert, scheint wieder zu gehen. Der DP bleibt weiterhin vorhanden und der Rollo lässt sich damit steuern. Keine Fehler in der Log.

Vielen Dank
