### ISSUE TITLE
nach Update auf JS-Controller 5.x funktioniert die Aktualisierung zwischen FHEM und ioBroker nicht mehr

### ISSUE THREAD

**Issue by evazoe1410** [iobroker-community-adapters/ioBroker.fhem#214]
**Describe the bug**  
nach Update auf JS-Controller 5.x funktioniert die automatische Aktualisierung zwischen FHEM und ioBroker nicht mehr, erst nach Adapter-Neustart werden die dann aktuellen Werte übertragen.

**Versions:**  
 - Adapter version: 2.03
 - JS-Controller version: 5.05
 - Node version: 16.20.0
 - Operating system: Debian Buster

**Comment by mcm1957** [comment]
Wie ist das gemeint?

Beim Upgrade ist ja das System gestoppt und nach dem Update werden alle Adapter neu gestartet. 
Ist  gemeint dass nach dem erstmaligen Start keine Dsten übertragen wurden und ein weiterer Adapterstart notwendig war?

Gibts irgenwelche relevante Logeinträge?

**Comment by evazoe1410** [comment]
seit dem Update auf JS-Controller funktioniert die automatische Aktualisierung der Datenpunkte im ioBroker nach Änderungen in den FHEM-Objekten nicht mehr. Nach Neustart des FHEM-Adapters werden dann die aktuellen Werte einmalig nach ioBroker übertragen. Im Debuglog sieht es so aus, dass die Events aus FHEM schon im ioBroker ankommen, dann aber nicht mehr verarbeitet werden, Fehlermeldungen sind keine vorhanden.

**Comment by mcm1957** [comment]
Danke f d klarstellung

**Comment by Apollon77** [comment]
Debug Log sagt was?

**Comment by VonDerTanne** [comment]
Selbes Verhalten hier mit 2 separaten FHEM-Instanzen auf getrennten Systemen. Vermutlich gleiches Problem wie Issue #213 (bzgl. Logs)

**Comment by VonDerTanne** [comment]
@Apollon77 zur Beantwortung Deiner Frage (auch im anderen Issue vermerkt):

Nachtrag: beim Adapter Start bringt er auch folgende weitergende Fehlermeldung:

2023-06-21 10:00:40.368 - error: fhem.0 (434372) uncaught exception: Parameter "options" needs to be a real object but type "number" has been passed
2023-06-21 10:00:40.369 - error: fhem.0 (434372) Error: Parameter "options" needs to be a real object but type "number" has been passed
at Function.assertObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:301:19)
at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7429:23)
at setStateDoWrite (/opt/iobroker/node_modules/iobroker.fhem/main.js:3099:13)
at setStateDo (/opt/iobroker/node_modules/iobroker.fhem/main.js:3093:13)
at Immediate.processSetState (/opt/iobroker/node_modules/iobroker.fhem/main.js:3077:5)
at processImmediate (node:internal/timers:478:21)

**Comment by LausiD** [comment]
Bitte FHEM Adapter aus github aktualisieren.....fix 25.06.23

**Comment by mcm1957** [comment]
@LausiD 

How about creating a new release`? Look like you have enough rights here?
Feel free to ask if you need support.

Of coiurse I can create a new release too if you do not have time to do. Please let me know.

**Comment by mcm1957** [comment]
fixed with 2.0.4 which incorporates current github level updated by LausiD (Thanks!)

Please open new issue if still open problems exist.
